### ISSUE TITLE
Might be missing target platforms

### ISSUE THREAD

**Issue by justinwoo** [justinwoo/easy-dhall-nix#23]
e.g. aarch64

https://github.com/justinwoo/easy-purescript-nix/issues/104

**Comment by trskop** [comment]
I don't see anything other than x86 in https://github.com/dhall-lang/dhall-haskell/releases
Any idea where we could get them from?

**Comment by justinwoo** [comment]
Good question, maybe this is a dud issue

**Comment by sjakobi** [comment]
Related: https://github.com/dhall-lang/dhall-haskell/issues/1758

**Comment by justinwoo** [comment]
Not actionable
